# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
